--- @class Rotoris.LuaCanvas.CanvasContext
--- @field paints Rotoris.LuaCanvas.PaintCache
--- @field images Rotoris.LuaCanvas.ImageCache
--- @field fonts Rotoris.LuaCanvas.FontCache
--- @field clear fun(self: Rotoris.LuaCanvas.CanvasContext, hexColor?: string) Clears the canvas with the specified color or transparent if no color is provided.
--- @field set_paint fun(self: Rotoris.LuaCanvas.CanvasContext, name: string) Sets the current paint by name from the PaintCache.
--- @field draw_line fun(self: Rotoris.LuaCanvas.CanvasContext, x1: number, y1: number, x2: number, y2: number) Draws a line between two points.
--- @field draw_oval fun(self: Rotoris.LuaCanvas.CanvasContext, x: number, y: number, rx: number, ry: number) Draws an oval centered at (x, y) with radii rx and ry.
--- @field draw_rect fun(self: Rotoris.LuaCanvas.CanvasContext, x: number, y: number, width: number, height: number, options?: table) Draws a rectangle with optional rounded corners.
--- @field draw_circle fun(self: Rotoris.LuaCanvas.CanvasContext, cx: number, cy: number, radius: number) Draws a circle centered at (cx, cy) with the specified radius.
--- @field draw_text fun(self: Rotoris.LuaCanvas.CanvasContext, text: string, x: number, y: number, fontSize?: number, familyName?: string) Draws text at the specified position.
--- @field measure_text fun(self: Rotoris.LuaCanvas.CanvasContext, text: string, fontSize?: number, familyName?: string): SkiaSharp.SKRect Measures the bounding box of the specified text.
--- @field draw_image fun(self: Rotoris.LuaCanvas.CanvasContext, filePath: string, x: number, y: number, width?: number, height?: number) Draws an image from the specified file path.
--- @field create_path fun(self: Rotoris.LuaCanvas.CanvasContext): Rotoris.LuaCanvas.CanvasPath Creates a new CanvasPath object.
--- @field draw_path fun(self: Rotoris.LuaCanvas.CanvasContext, action: fun(path: Rotoris.LuaCanvas.CanvasPath)) Draws a path defined by the provided action.
--- @field translate fun(self: Rotoris.LuaCanvas.CanvasContext, dx: number, dy: number) Translates the canvas by the specified offsets.
--- @field scale fun(self: Rotoris.LuaCanvas.CanvasContext, sx: number, sy: number) Scales the canvas by the specified factors.
--- @field rotate fun(self: Rotoris.LuaCanvas.CanvasContext, degrees: number) Rotates the canvas by the specified angle in degrees.
--- @field save fun(self: Rotoris.LuaCanvas.CanvasContext) Saves the current canvas state.
--- @field restore fun(self: Rotoris.LuaCanvas.CanvasContext) Restores the canvas to the last saved state.
--- @field delay fun(self: Rotoris.LuaCanvas.CanvasContext, milliseconds: number) Delays execution for the specified number of milliseconds.
--- @field done fun(self: Rotoris.LuaCanvas.CanvasContext): boolean Marks the drawing as done and returns true.

--- @class Rotoris.LuaCanvas.CanvasContext.Args
--- @field CanvasWidth number
--- @field CanvasHeight number
--- @field DeltaTime number