name: Build, Test, and Beta Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: windows-latest
    outputs:
      artifact_name: ${{ steps.set_artifact_name.outputs.name }}
    env:
      BUILD_OUTPUT_PATH: publish-output

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 
        
    - name: Build Release Version
      run: dotnet publish Rotoris.slnx -c Release -o ${{ env.BUILD_OUTPUT_PATH }}
      
    - name: Run Tests
      run: dotnet test RotorisLib.Tests/RotorisLib.Tests.csproj --configuration Release

    - name: Set Artifact Name
      id: set_artifact_name
      shell: pwsh
      run: '"name=release-files-${{ github.sha }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Append'

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.set_artifact_name.outputs.name }}
        path: ${{ env.BUILD_OUTPUT_PATH }}
        retention-days: 1

  release:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    env:
      COMMIT_SHA: ${{ github.sha }}
      
    steps:
    - name: Get Unix Timestamp and Set Tag Name
      run: |
        TIMESTAMP=$(date +%s)
        echo "TAG_NAME=Rotoris_beta_${TIMESTAMP}" >> $GITHUB_ENV
        echo "ZIP_FILE_NAME=Rotoris-beta-${TIMESTAMP}.zip" >> $GITHUB_ENV
        echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV
        
    - name: Download Compiled Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.artifact_name }}
        path: downloaded-files/

    - name: Add app.ini Version Info
      run: |
        VERSION_STRING="${{ env.TIMESTAMP }}"
        echo -e "[Version]\nAppVersion=${VERSION_STRING}" > downloaded-files/app.ini

    - name: Create Zip Archive
      run: |
        cd downloaded-files
        zip -r ../${{ env.ZIP_FILE_NAME }} .
        
    - name: Create New Beta Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: Automated Beta Build (Rotoris Beta ${{ env.TIMESTAMP }})
        body: |
          This is an automated beta build of the Rotoris project, built from commit ${{ env.COMMIT_SHA }}.
        prerelease: true
        files: ${{ env.ZIP_FILE_NAME }}